---

- hosts: all
  become: true

  tasks:
  - name: update repo index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest  
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    yum:
      name: apache2    
      state: latest
    when: ansible_distribution == "CentOS"


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest



